import type { NextPage } from "next";
import Head from "next/head";
import { PokemonSprites } from "pokenode-ts";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const pokemon = trpc.useQuery(["pokemon-get", { id: 2 }]);

  return (
    <>
      <Head>
        <title>PokeDex on Blais.gg</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="" href="" />
      </Head>

      <main className="container mx-auto flex flex-col">
        <PokemonCard
          name={pokemon.data?.name}
          type1={""}
          type2={""}
          sprite={
            pokemon.data?.sprites.front_default != null
              ? pokemon.data?.sprites.front_default
              : undefined
          }
        />
      </main>
    </>
  );
};

type PokemonCardProps = {
  name?: string;
  type1?: string;
  type2?: string;
  sprite?: string;
};

const PokemonCard = ({ name, type1, type2, sprite }: PokemonCardProps) => {
  return (
    <section className="flex flex-col w-48 h-48 justify-center p-6 rounded-md border-4 border-gray-400 motion-safe:hover:scale-110 duration-500">
      <h3 className="font-bold text-gray-300">{name}</h3>
      <p className="text-gray-400"></p>
      <img src={sprite} className="w-full" />
    </section>
  );
};

export default Home;
