import type { NextPage } from "next";
import Head from "next/head";
import React, { useState } from "react";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>PokeDex on Blais.gg</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="" href="" />
      </Head>

      <main className="p-6 justify-center items-center">
        <div className="container flex flex-wrap items-center justify-start gap-5">
          {AllPokemon()}
        </div>
      </main>
    </>
  );
};

type PokemonCardProps = {
  ID: number;
  name: string;
  types: string[];
  sprite: string;
};

function AllPokemon() {
  const names = trpc.useQuery(["pokemon-get-names", { id: 0 }]);
  const PokeNames: PokemonCardProps[] = [];
  for (let i = 0; i < 905; i++) {
    PokeNames.push({
      ID: i + 1,
      name: names.data?.results[i]?.name as string,
      types: [],
      sprite: `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${
        i + 1
      }.png`,
    });
  }
  return (
    <>
      {PokeNames.map((item, index) => {
        return PokeButton(item);
      })}
    </>
  );
}

function PokeButton(Poke: PokemonCardProps) {
  const [PokeButton, setPokeButton] = useState(true);

  const [bStr, setbStr] = useState(
    "flex flex-col w-48 h-48 justify-center items-center bg-grey-400 p-6 rounded-md border-4 motion-safe:hover:scale-105 duration-500"
  );

  return (
    <button
      onClick={() => {
        setPokeButton(!PokeButton);
        setbStr(
          !PokeButton
            ? "flex flex-col w-48 h-48 justify-center items-center bg-grey-400 p-6 rounded-md border-4 motion-safe:hover:scale-105 duration-500"
            : "flex flex-col w-48 h-48 justify-center items-center bg-green-300 p-6 rounded-md border-4 motion-safe:hover:scale-105 duration-500"
        );
      }}
      className={bStr}
    >
      <h3 className="font-bold text-gray-300">{Poke.name}</h3>
      <p className="text-gray-400">{Poke.ID}</p>
      <img src={Poke.sprite} className="w-full" />
    </button>
  );
}

export default Home;
