import classNames from "classnames";
import type { NextPage } from "next";
import Head from "next/head";
import React, { useState, KeyboardEvent, useEffect } from "react";
import { number } from "zod";
import { trpc } from "../utils/trpc";
import { myWordsArray } from "../utils/words";

enum LetterStatus {
  Unknown = "bg-grey-400",
  Correct = "bg-green-400",
  Misplaced = "bg-yellow-400",
  Wrong = "bg-red-400",
}

type MyProps = {
  letter: string;
  status: LetterStatus;
};

function LetterBox(props: MyProps) {
  let divClass: string =
    "flex flex-col w-14 h-14 justify-center items-center p-6 rounded-md border-4 motion-safe:hover:scale-105 duration-500 " +
    props.status;
  return (
    <div className={divClass}>
      <h3 className="font-bold text-gray-600">{props.letter}</h3>
    </div>
  );
}

const Home: NextPage = () => {
  const [theWord, setTheWord] = useState(
    myWordsArray[
      Math.round(Math.random() * myWordsArray.length + 0.5)
    ]?.toUpperCase() as string
  );

  const [currentWord, setCurrentWord] = useState("");

  const handleKeyboardEvent = (e: KeyboardEvent<HTMLElement>) => {
    setCurrentWord(e.key);
  };

  return (
    <>
      <Head>
        <title>Wordle on Blais.gg</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="" href="" />
      </Head>

      <main
        className="p-6 justify-center items-center overflow-hidden h-screen w-screen"
        tabIndex={0}
        onKeyPressCapture={handleKeyboardEvent}
      >
        <div className="container flex flex-wrap items-center justify-center gap-5">
          <LetterBox
            letter={currentWord}
            status={LetterStatus.Unknown}
          ></LetterBox>
        </div>
      </main>
    </>
  );
};

export default Home;
